name: two_space_app
description: "A secure and feature-rich messenger for the TwoSpace ecosystem."
publish_to: 'none'
version: 0.1.6+12

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  # ===== State Management =====
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  # ===== Monitoring & Error Tracking =====
  sentry_flutter: ^8.14.2
  logger: ^2.4.0

  # ===== Security =====
  flutter_secure_storage: ^9.2.2
  local_auth: ^2.2.0

  # ===== UI & Theming =====
  google_fonts: ^6.2.1
  flutter_dotenv: ^5.1.0
  emoji_picker_flutter: ^2.2.0
  cached_network_image: ^3.3.1
  qr_flutter: ^4.1.0

  # ===== File & Path =====
  file_picker: ^8.0.6
  path_provider: ^2.1.3
  image_picker: ^1.1.2
  open_file: ^3.3.2

  # ===== Networking & API =====
  http: ^1.2.1
  dio: ^5.5.0+1
  connectivity_plus: ^6.0.3

  # ===== Database =====
  sqflite: ^2.3.3+1
  drift: ^2.18.0

  # ===== Media =====
  audioplayers: ^6.0.0

  # ===== Utilities =====
  package_info_plus: ^8.0.0
  url_launcher: ^6.3.0
  share_plus: ^9.0.0
  permission_handler: ^11.3.1
  device_info_plus: ^10.1.0
  app_links: ^6.0.0
  flutter_displaymode: ^0.7.0
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.11
  riverpod_generator: ^2.4.0
  drift_dev: ^2.18.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - .env
    - assets/
    - assets/images/
    - assets/fonts/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/icon/icon.png"
    background_color: "#000000"
    theme_color: "#000000"
  windows:
    generate: true
    image_path: "assets/icon/icon.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/icon/icon.png"
